# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pymc-util',
                'doc_host': 'https://spdrnl.github.io',
                'git_url': 'https://github.com/spdrnl/pymc-util',
                'lib_path': 'pymc_util'},
  'syms': {'pymc_util.core': {'pymc_util.core.foo': ('core.html#foo', 'pymc_util/core.py')}}}